
const printSites = [
// presuming auto start, just click to advance, update tour
	{
		id: 1,
		core: 1, //merc as placeholder
		minor: 0,
    "x": 6655,
    "y": 4476,
		r: 0,
		scale: 4,
		tile:212,
		// mapName: 'none',
		name: "Printing in Venice, An Introduction",
		// type: 'map',
		// minor: 0,
		// author: 'Giovanni Merlo',
		// title: 'Vero e real disegno della inclita cita di Venetia',
		// publisher: '[Venice] : Stefano Scolari forma in Venetia a S. Zulian',
		// date: '1676',
		// physical: '1 view : hand col. ; 780 x 1,594 mm. (neat line) on 3 composite sheets.',
		// detail: '',
		src: ['./img/Pliny_thumbnail.jpg', './img/Le%20Poesie_thumbnail.jpg', './img/Eusebio_De%20Evangelica_thumbnail.jpg'],
		narrative: ['Within fifteen years of the publication of Gutenberg’s Bible in Mainz, Germany, printers began to spread out across Europe. By the 1460s, print shops had been set up in Venice, all run by craftsmen who had immigrated there in search of work. While these printers were no doubt drawn to the intellectual community of scholars and teachers in Venice, they also would have been attracted to its cosmopolitanism. Venice incorporated residential communities from many cultures, as well as travelers and merchants who regularly visited the city.', 'By the mid-16th century, Venice was the powerhouse of printing in Europe. Printers produced all kinds of books, from large, elaborate folios to small, portable books meant for personal study. They also produced a wide variety of ephemera -- inexpensive single sheets that provided news or entertainment and were not intended to be saved. Some booksellers maintained upscale shops while others peddled their wares from a stall or simply stood on Rialto Bridge calling out to potential customers. Essentially, books, and their makers and sellers, were as varied as the inhabitants of and travelers to Venice.', 'The material included here is not a complete survey of the Venetian book trade or religious communities of the period, but works to provide a glimpse of how printers, publishers, and booksellers shaped – and were shaped by – religious, political, intellectual, and social life in Venice.']
	},
	{
		id: 2,
		core: 2, //merc as placeholder
		minor: 0,
    "x": 6655,
    "y": 4476,
		r: 0,
		scale: 4,
		tile:212,
		// mapName: 'none',
		name: "Printing in Venice, At the Sign of...",
		// type: 'map',
		// author: 'Giovanni Merlo',
		// title: 'Vero e real disegno della inclita cita di Venetia',
		// publisher: '[Venice] : Stefano Scolari forma in Venetia a S. Zulian',
		// date: '1676',
		// physical: '1 view : hand col. ; 780 x 1,594 mm. (neat line) on 3 composite sheets.',
		// detail: '',
		src: ['./img/Predica del Reverendo_thumbnail.jpg', './img/Detail%20of%20Compilatio_thumbnail.jpg'],
		subtitles: ['At the Sign of… ', 'The Inquisition and the Venetian Book Trade'],
		narrative: ['Booksellers often included information about the location of their shop on the title page or in the colophon of their books. While sometimes this information was merely textual (e.g. “at the sign of the Diamond”) often it was visual as well, in the form of the printer’s device, which would also have appeared on the sign at the physical shop. These devices not only linked books to specific locations, but also worked to form part of the visual landscape of Venice in the period. Rialto Bridge, and the neighborhoods that surrounded it, would have been filled with all kinds of shops and signs. These signs functioned as advertising, competing for the attention – and the money – of customers both old and new.', 'In 1559 Pope Paul IV issued a new Index of Prohibited Books, enlarging the previous index of 1554-55. In Venice, booksellers were required to present inventories of books they had in stock. Many booksellers resolved to disobey these instructions and would neither print the index or supply inventories. Melchiorre Sessa was particularly hopeful that the book trade might put up a united front; he censored booksellers (including Vincenzo Valgrisi) who gave in to pressure and submitted inventories. Due to the prohibition on printing certain books as a result of the Counter-Reformation, printers were required to secure the necessary permissions from Italian authorities before conducting their work. In the early 1550s, despite failing to secure such permissions, Giovanni Griffio continued printing, resulting in a fine of 25 ducats and a sentence of one month in prison.']
	},
	{
		id: 3,
		core: 10, //speyer
		minor: 1,
    "x": 7674,
    "y": 4142,
		r: 0,
		scale: 4,
		tile:212,
		// mapName: 'barbari',
		name: "Speyer, the First Printer in Venice",
		// type: 'map',
		// author: "Jacopo de' Barbari",
		// title: 'La Pianta di Venezia di Jacopo de’ Barbari',
		// publisher: '[Venice : Anton Kolb?]',
		// date: '1500',
		// physical: '1 view on 6 sheets : woodcut ; 1,345 x 2,818 mm.',
		// detail: '',
		src: './img/Pliny_thumbnail.jpg'
	},
	{
		id: 4,
		core: 10, //speyer
		minor: 14,
    "x": 7674,
    "y": 4142,
		r: 0,
		scale: 4,
		tile:212,
		// mapName: 'barbari',
		name: "Speyer's Final Publication",
		// type: 'map',
		// author: "Jacopo de' Barbari",
		// title: 'La Pianta di Venezia di Jacopo de’ Barbari',
		// publisher: '[Venice : Anton Kolb?]',
		// date: '1500 ',
		// physical: '1 view on 6 sheets : woodcut ; 1,345 x 2,818 mm.',
		// detail: '',
		src: './img/Augustine_thumbnail.jpg',
	},
	{
		id: 5,
		core: 41, //rialto
		minor: 0,
    "x": 6386,
    "y": 3467,
		r: 0,
		scale: 4,
		tile:212,
		// mapName: 'barbari',
		name: "The Rialto's Printing Markets",
		// type: 'map',
		// author: "Jacopo de' Barbari",
		// title: 'La Pianta di Venezia di Jacopo de’ Barbari',
		// publisher: '[Venice : Anton Kolb?]',
		// date: '1500 ',
		// physical: '1 view on 6 sheets : woodcut ; 1,345 x 2,818 mm.',
		// detail: '',
		src: './img/Le%20Poesie_thumbnail.jpg'
	},
	{
		id: 6,
		core: 41, //rialto sign of
		minor: 11,
    "x": 6386,
    "y": 3467,
		r: 0, //
		scale: 4,
		tile:212,
		// mapName: 'barbari',
		name: "The Rialto: Perderzano's Bookshop",
		// type: 'map',
		// author: "Jacopo de' Barbari",
		// title: 'La Pianta di Venezia di Jacopo de’ Barbari',
		// publisher: '[Venice : Anton Kolb?]',
		// date: '1500 ',
		// physical: '1 view on 6 sheets : woodcut ; 1,345 x 2,818 mm.',
		// detail: '',
		src: './img/Sonetti%20Canzoni_thumbnail.jpg'
	},
	{
		id: 7,
		core: 41, //rialto music
		minor: 5,
    "x": 6386,
    "y": 3467,
		r: 0, //
		scale: 4,
		tile:212,
		// mapName: 'barbari',
		name: "The Rialto: Scotto and Gardano's Music Printing",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Jacopo de' Barbari",
		// title: 'La Pianta di Venezia di Jacopo de’ Barbari',
		// publisher: '[Venice : Anton Kolb?]',
		// date: '1500 ',
		// physical: '1 view on 6 sheets : woodcut ; 1,345 x 2,818 mm.',
		// detail: '',
		src: './img/Gardano_thumbnail.jpg'
	},
	{
		id: 8,
		core: 46, //merc
		minor: 0,
    "x": 6655,
    "y": 4476,
		r: 0,
		scale: 4,
		tile:212,
		// mapName: 'barbari',
		name: 'Merceria: A Printing Hub',
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Jacopo de' Barbari",
		// title: 'La Pianta di Venezia di Jacopo de’ Barbari',
		// publisher: '[Venice : Anton Kolb?]',
		// date: '1500 ',
		// physical: '1 view on 6 sheets : woodcut ; 1,345 x 2,818 mm.',
		// detail: '',
		src: './img/Eusebio_De%20Evangelica_thumbnail.jpg'
	},
	{
		id: 9,
		core: 46, //merc
		minor: 2,
    "x": 6655,
    "y": 4476,
		r: 0,
		scale: 4,
		tile:212,
		// mapName: 'barbari',
		name: "Merceria: Bertacagno's Printshop",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Jacopo de' Barbari",
		// title: 'La Pianta di Venezia di Jacopo de’ Barbari',
		// publisher: '[Venice : Anton Kolb?]',
		// date: '1500 ',
		// physical: '1 view on 6 sheets : woodcut ; 1,345 x 2,818 mm.',
		// detail: '',
		src: './img/Le%20Giocose%20Moderne_thumbnail.jpg'
	},
	{
		id: 10,
		core: 46, //merc
		minor: 3,
    "x": 6655,
    "y": 4476,
		r: 0,
		scale: 4,
		tile:212,
		// mapName: 'barbari',
		name: "Merceria: Arrivabene's Bookshop",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Jacopo de' Barbari",
		// title: 'La Pianta di Venezia di Jacopo de’ Barbari',
		// publisher: '[Venice : Anton Kolb?]',
		// date: '1500 ',
		// physical: '1 view on 6 sheets : woodcut ; 1,345 x 2,818 mm.',
		// detail: '',
		src: './img/Predica del Reverendo_thumbnail.jpg'
	},
	{
		id: 11,
		core: 46, //merc
		minor: 4,
    "x": 6655,
    "y": 4476,
		r: 0,
		scale: 4,
		tile:212,
		// mapName: 'bordone',
		name: "Merceria: Griffio Publishers",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Benedetto Bordone",
		// title: 'Isolario di Benedetto Bordone',
		// publisher: 'Venice, N. Zoppoino',
		// date: '1534',
		// physical: '(fol.). 10 p.l., lxxiiii numb. l : ill. (maps, some double)',
		// detail: '',
		src: './img/L%27arte%20oratoria_thumbnail.jpg'
	},
	{
		id: 12,
		core: 45, //san marco
		minor: 10,
    "x": 5655,
    "y": 5476,
		r: 0,
		scale: 4,
		tile:158,
		// mapName: 'forlani',
		 name: "San Marco: Valgrisi's Bookshop",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Paolo Forlani",
		// title: 'Venetia',
		// publisher: '[Venice] : ex aeneis formis Bolognini Zalterii, M. D. XVI',
		// date: '1566',
		// physical: '	1 view ; 360 x 731 mm. (neat line), on sheet 444 x 744 mm.',
		// detail: '',
		src: './img/Il%20Terentio%20Latino_thumbnail.jpg'
	},
	{
		id: 13,
		core: 38, //humanist
		minor: 0,
    "x": 4735,
    "y": 3442,
		r: 0,
		scale: 5,
		tile:128,
		// mapName: 'forlaniAligned',
		 name: "The Humanist Printer: Aldus Manutius",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Paolo Forlani",
		// title: 'Venetia',
		// publisher: '[Venice] : ex aeneis formis Bolognini Zalterii, M. D. XVI',
		// date: '1566',
		// physical: '	1 view ; 360 x 731 mm. (neat line), on sheet 444 x 744 mm.',
		// detail: '',
		src: './img/Angelo%20Poliziano.%20Opera_thumbnail.jpg'},
	{
		id: 14,
		core: 38, //humanist
		minor: 6,
    "x": 4735,
    "y": 3442,
		r: 0,
		scale: 5,
		tile:128,
		// mapName: 'bertilliAligned',
		 name: "Aldine Device",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Donato Bertelli",
		// title: 'Venetia',
		// publisher: '[Venice] : alla libraria del segno de S. Marco in merzaria Donato Bertelli',
		// date: '1570',
		// physical: '1 view ; 284 x 584 mm. (neat line), 376 x 585 mm.',
		// detail: '',
		src: './img/Inscriptiones%20Antiquae_thumbnail.jpg'
	},
	{
		id: 15,
		core: 38, //humanist
		minor: 7,
    "x": 4735,
    "y": 3442,
		r: 0,
		scale: 5,
		tile:128,
		// mapName: 'florimi',
		 name: "Aldine Italic",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Matteo Florimi.",
		// title: 'Venetia',
		// publisher: '[Siena?] : Matteo Florimi formis,',
		// date: '1597',
		// physical: '1 view ; 291 x 508 mm. (neat line), on sheet remargined to 451 x 591 mm.',
		// detail: '',
		src: './img/Juvenal_thumbnail.jpg'
	},
	{
		id: 16,
		core: 38, //humanist
		minor: 8,
    "x": 4735,
    "y": 3442,
		r: 0,
		scale: 5,
		tile:128,
		// mapName: 'florimiAligned',
		 name: "Aldus' Eulogy",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Matteo Florimi.",
		// title: 'Venetia',
		// publisher: '[Siena?] : Matteo Florimi formis,',
		// date: '1597',
		// physical: '1 view ; 291 x 508 mm. (neat line), on sheet remargined to 451 x 591 mm.',
		// detail: '',
		src: './img/Lactantius_thumbnail.jpg'
	},
	{
		id: 17,
		core: 38, //humanist
		minor: 9,
    "x": 4735,
    "y": 3442,
		r: 0,
		scale: 5,
		tile:128,
		// mapName: 'florimiAligned',
		 name: "Aldine Press Booklist",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Matteo Florimi.",
		// title: 'Venetia',
		// publisher: '[Siena?] : Matteo Florimi formis,',
		// date: '1597',
		// physical: '1 view ; 291 x 508 mm. (neat line), on sheet remargined to 451 x 591 mm.',
		// detail: '',
		src: './img/Epitome%20Orthographiae_thumbnail.jpg'
	},
	{
		id: 18,
		core: 44, //sessa
		minor: 0,
		"x": 7066,
    "y": 3988,
		r: 0,
		scale: 4,
		tile:238,
		// mapName: 'florimiAligned',
		 name: "Sessa Family Publishing",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Matteo Florimi.",
		// title: 'Venetia',
		// publisher: '[Siena?] : Matteo Florimi formis,',
		// date: '1597',
		// physical: '1 view ; 291 x 508 mm. (neat line), on sheet remargined to 451 x 591 mm.',
		// detail: '',
		src: './img/Detail%20of%20Compilatio_thumbnail.jpg'
	},
	{
		id: 19,
		core: 51, //exports
		minor: 0,
    "x": 13072,
    "y": 6916,
		r: 0,
		scale: 4,
		tile:238,
		// mapName: 'florimiAligned',
		 name: "Printing for Export",
		// type: 'map',
		// cluster: null,
		// clusterId: null,
		// author: "Matteo Florimi.",
		// title: 'Venetia',
		// publisher: '[Siena?] : Matteo Florimi formis,',
		// date: '1597',
		// physical: '1 view ; 291 x 508 mm. (neat line), on sheet remargined to 451 x 591 mm.',
		// detail: '',
		src: './img/barbari-1.jpg'
	}


];

export default printSites;
